Write a function to compute 5/0 and use try/except to catch the exceptions.

In [7]:
def exception_testing():
    return 5/0

try:
    exception_testing()
except ZeroDivisionError:#
    print("Don't divide a number by ZERO!!")
except:
    print("Other type of exception")


# exception_testing()

Don't divide a number by ZERO!!


Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]

verbs=["play","watch"]

objects=["Baseball","Cricket"]

**Output should come as below:**

Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [8]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
sentence = [(i + " "+ j + " "+ k) for i in subjects for j in verbs for k in objects]
print(sentence)
for x in sentence:
  print(x)

['Americans play Baseball', 'Americans play Cricket', 'Americans watch Baseball', 'Americans watch Cricket', 'Indians play Baseball', 'Indians play Cricket', 'Indians watch Baseball', 'Indians watch Cricket']
Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
**HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.**

In [10]:
import numpy as np  
def gen_geo_prog_matrix(ipvector, n, increasing=False):
  if not increasing:        
    op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
  elif increasing:
    op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n) 
  return op_matx
# print("------------OUTPUT-------------")
input_number = input("Enter Your Number -> ")
inputvector =  list(map(int, str(input_number)))  
print("\n", "The input array Before NP array :",inputvector,"\n")
inputvector = np.array(inputvector)
print("The input array After NP array :",inputvector,"\n")
no_col_opmat = input("Enter No of Col for O/p Matrix-> ")
no_col_opmat = int(no_col_opmat)
op_matrix_dec_order = gen_geo_prog_matrix(inputvector,no_col_opmat,False)
op_matrix_inc_order = gen_geo_prog_matrix(inputvector,no_col_opmat,True)


print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matrix_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matrix_inc_order,"\n")

Enter Your Number -> 345678

 The input array Before NP array : [3, 4, 5, 6, 7, 8] 

The input array After NP array : [3 4 5 6 7 8] 

Enter No of Col for O/p Matrix-> 7
Number of columns in output matrix should be: 7 

Vander matrix of the input array in decreasing order of powers:

 [[   729    243     81     27      9      3      1]
 [  4096   1024    256     64     16      4      1]
 [ 15625   3125    625    125     25      5      1]
 [ 46656   7776   1296    216     36      6      1]
 [117649  16807   2401    343     49      7      1]
 [262144  32768   4096    512     64      8      1]] 

Vander matrix of the input array in increasing order of powers:

 [[     1      3      9     27     81    243    729]
 [     1      4     16     64    256   1024   4096]
 [     1      5     25    125    625   3125  15625]
 [     1      6     36    216   1296   7776  46656]
 [     1      7     49    343   2401  16807 117649]
 [     1      8     64    512   4096  32768 262144]] 

